### ISSUE TITLE
Issues Launching on Windows

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlusRegressionTool#2]
C:\MJW Git\EnergyPlusRegressionTool>C:\Python34\python.exe eplus_regression_runner
Traceback (most recent call last):
File "C:\MJW Git\EnergyPlusRegressionTool\epregressions\main_window.py", line 311, in load_settings
project_tree = json.loads(file_content)
File "C:\Python34\lib\json_init_.py", line 318, in loads
return _default_decoder.decode(s)
File "C:\Python34\lib\json\decoder.py", line 343, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "eplus_regression_runner", line 16, in 
main_window = RegressionGUI()
File "C:\MJW Git\EnergyPlusRegressionTool\epregressions\main_window.py", line 152, in init
self.load_settings(None)
File "C:\MJW Git\EnergyPlusRegressionTool\epregressions\main_window.py", line 312, in load_settings
except json.decoder.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'

**Comment by Myoldmopar** [comment]
Closing this.
