### ISSUE TITLE
Run silently fails and hangs due to file encoding error

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlusRegressionTool#32]
I was trying to run all tests, and it would just hang, system monitor showed no activity.

After debug, it seems that `testfiles/AirflowNetwork_MultiAirLoops.idf` has degree signs `°` that aren't UTF-8 encoded.
While this issue could be fixed by actually encoding that file correctly, we should catch that stuff.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/julien/Software/Others/EnergyPlusRegressionTool/epregressions/runtests.py", line 221, in run_build
    idf_text = f_idf.read()  # EDWIN: Make sure this reads the IDF properly
  File "/home/julien/.pyenv/versions/3.7.2/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 1446: invalid start byte
```

**Comment by Myoldmopar** [comment]
This is fixed via #34.  I will be using the cpu count fix in #27 to fix #33.
